!SESSION 2021-06-03 12:06:38.701 -----------------------------------------------
eclipse.buildId=Version 1.4.2
java.version=1.8.0_252
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_CA
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY com.st.stm32cube.ide.mcu.informationcenter 1 1 2021-06-03 12:07:13.097
!MESSAGE Log4j initialized with config file D:\GitHub\STM32f7_freeRTOS\.metadata\.log4j.xml

!ENTRY com.st.stm32cube.ide.mcu.ide 1 1 2021-06-03 12:07:22.421
!MESSAGE Started RMI Server, listening on port 41337

!ENTRY com.st.stm32cube.ide.mcu.ide 4 4 2021-06-03 12:07:22.976
!MESSAGE com.st.stm32cube.ide.mcu.ide/META-INF/version/build_ref file not found, build reference will not be reported into properties

!ENTRY org.eclipse.cdt.core 1 0 2021-06-03 13:27:48.264
!MESSAGE Indexed 'C1' (0 sources, 0 headers) in 0.003 sec: 0 declarations; 0 references; 0 unresolved inclusions; 0 syntax errors; 0 unresolved names (0%)

!ENTRY org.eclipse.cdt.core 1 0 2021-06-03 13:27:59.451
!MESSAGE Indexed 'C1' (21 sources, 21 headers) in 2.44 sec: 1,983 declarations; 13,854 references; 1 unresolved inclusions; 83 syntax errors; 6,404 unresolved names (29%)

!ENTRY org.eclipse.cdt.core 1 0 2021-06-03 13:40:33.798
!MESSAGE Indexed 'C1' (30 sources, 98 headers) in 1.78 sec: 6,723 declarations; 37,095 references; 1 unresolved inclusions; 8 syntax errors; 14 unresolved names (0.032%)

!ENTRY org.eclipse.jface 2 0 2021-06-03 13:40:40.261
!MESSAGE Ignored reentrant call while viewer is busy. This is only logged once per viewer instance, but similar calls will still be ignored.
!STACK 0
java.lang.RuntimeException
	at org.eclipse.jface.viewers.ColumnViewer.checkBusy(ColumnViewer.java:764)
	at org.eclipse.jface.viewers.ColumnViewer.update(ColumnViewer.java:543)
	at org.eclipse.ui.navigator.CommonViewer.update(CommonViewer.java:512)
	at org.eclipse.jface.viewers.StructuredViewer.update(StructuredViewer.java:1965)
	at org.eclipse.ui.internal.navigator.resources.nested.NestedProjectsLabelProvider.lambda$2(NestedProjectsLabelProvider.java:87)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

!ENTRY org.eclipse.cdt.core 1 0 2021-06-03 13:45:36.493
!MESSAGE Indexed 'C1' (30 sources, 99 headers) in 2.06 sec: 7,229 declarations; 41,109 references; 0 unresolved inclusions; 1 syntax errors; 0 unresolved names (0%)

!ENTRY com.st.stm32cube.ide.mcu.debug.jlink 1 0 2021-06-03 14:50:47.260
!MESSAGE Using automatic SWV detection; base: 4500000; minDiv: 1; maxSWO: 4500000; SWO: 4500000; CPU: 168000000; div: 37

!ENTRY com.st.stm32cube.ide.mcu.debug.swv 4 0 2021-06-03 14:51:34.452
!MESSAGE SWV Client received I/O Exception: Connection reset... trying to reconnect

!ENTRY com.st.stm32cube.ide.mcu.debug.swv 4 0 2021-06-03 14:51:36.502
!MESSAGE SWVClient - Failed to connect to Host: localhost Port: 2332

!ENTRY com.st.stm32cube.ide.mcu.debug.swv 4 0 2021-06-03 14:51:36.503
!MESSAGE Failed to reconnect and read data
!STACK 0
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at java.net.Socket.<init>(Socket.java:452)
	at java.net.Socket.<init>(Socket.java:229)
	at com.st.stm32cube.ide.mcu.debug.swv.core.SWVClient.connect(SWVClient.java:162)
	at com.st.stm32cube.ide.mcu.debug.swv.core.SWVClient.getNextByte(SWVClient.java:276)
	at com.st.stm32cube.ide.mcu.debug.swv.core.SWVClient.run(SWVClient.java:316)

!ENTRY org.eclipse.cdt.dsf.gdb 4 5012 2021-06-03 14:53:28.349
!MESSAGE Error in final launch sequence:

Failed to execute MI command:
target remote localhost:61234

Error message from debugger back end:
localhost:61234: The system tried to join a drive to a directory on a joined drive.
!STACK 1
org.eclipse.core.runtime.CoreException: Failed to execute MI command:
target remote localhost:61234

Error message from debugger back end:
localhost:61234: The system tried to join a drive to a directory on a joined drive.
	at org.eclipse.cdt.dsf.concurrent.Query.get(Query.java:112)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launchDebugSession(GdbLaunchDelegate.java:242)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launchDebugger(GdbLaunchDelegate.java:106)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launch(GdbLaunchDelegate.java:94)
	at com.st.stm32cube.ide.mcu.debug.launch.DSFDelegate.launch(DSFDelegate.java:299)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:860)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:719)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1017)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1220)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.Exception: localhost:61234: The system tried to join a drive to a directory on a joined drive.
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.processMIOutput(AbstractMIControl.java:993)
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.run(AbstractMIControl.java:822)
!SUBENTRY 1 org.eclipse.cdt.dsf.gdb 4 10004 2021-06-03 14:53:28.352
!MESSAGE Failed to execute MI command:
target remote localhost:61234

Error message from debugger back end:
localhost:61234: The system tried to join a drive to a directory on a joined drive.
!STACK 0
java.lang.Exception: localhost:61234: The system tried to join a drive to a directory on a joined drive.
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.processMIOutput(AbstractMIControl.java:993)
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.run(AbstractMIControl.java:822)

!ENTRY org.eclipse.cdt.dsf.gdb 4 5012 2021-06-03 14:55:00.162
!MESSAGE Error in final launch sequence:

Failed to execute MI command:
target remote localhost:2331

Error message from debugger back end:
localhost:2331: The system tried to join a drive to a directory on a joined drive.
!STACK 1
org.eclipse.core.runtime.CoreException: Failed to execute MI command:
target remote localhost:2331

Error message from debugger back end:
localhost:2331: The system tried to join a drive to a directory on a joined drive.
	at org.eclipse.cdt.dsf.concurrent.Query.get(Query.java:112)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launchDebugSession(GdbLaunchDelegate.java:242)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launchDebugger(GdbLaunchDelegate.java:106)
	at org.eclipse.cdt.dsf.gdb.launching.GdbLaunchDelegate.launch(GdbLaunchDelegate.java:94)
	at com.st.stm32cube.ide.mcu.debug.launch.DSFDelegate.launch(DSFDelegate.java:299)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:860)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:719)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1017)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1220)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.Exception: localhost:2331: The system tried to join a drive to a directory on a joined drive.
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.processMIOutput(AbstractMIControl.java:993)
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.run(AbstractMIControl.java:822)
!SUBENTRY 1 org.eclipse.cdt.dsf.gdb 4 10004 2021-06-03 14:55:00.163
!MESSAGE Failed to execute MI command:
target remote localhost:2331

Error message from debugger back end:
localhost:2331: The system tried to join a drive to a directory on a joined drive.
!STACK 0
java.lang.Exception: localhost:2331: The system tried to join a drive to a directory on a joined drive.
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.processMIOutput(AbstractMIControl.java:993)
	at org.eclipse.cdt.dsf.mi.service.command.AbstractMIControl$RxThread.run(AbstractMIControl.java:822)
!SESSION 2021-06-03 14:58:40.482 -----------------------------------------------
eclipse.buildId=Version 1.4.2
java.version=1.8.0_252
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_CA
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY com.st.stm32cube.ide.mcu.informationcenter 1 1 2021-06-03 15:02:52.470
!MESSAGE Log4j initialized with config file D:\GitHub\STM32f7_freeRTOS\.metadata\.log4j.xml

!ENTRY com.st.stm32cube.ide.mcu.ide 1 1 2021-06-03 15:02:56.123
!MESSAGE Started RMI Server, listening on port 41337

!ENTRY com.st.stm32cube.ide.mcu.ide 4 4 2021-06-03 15:02:56.715
!MESSAGE com.st.stm32cube.ide.mcu.ide/META-INF/version/build_ref file not found, build reference will not be reported into properties

!ENTRY org.eclipse.cdt.core 1 0 2021-06-03 17:18:28.137
!MESSAGE Indexed 'C1' (37 sources, 135 headers) in 2.39 sec: 12,931 declarations; 71,555 references; 2 unresolved inclusions; 137 syntax errors; 158 unresolved names (0.19%)

!ENTRY org.eclipse.cdt.core 1 0 2021-06-03 17:21:04.356
!MESSAGE Indexed 'C1' (37 sources, 135 headers) in 1.9 sec: 12,931 declarations; 71,555 references; 2 unresolved inclusions; 137 syntax errors; 158 unresolved names (0.19%)

!ENTRY org.eclipse.cdt.core 1 0 2021-06-03 17:23:08.994
!MESSAGE Indexed 'C1' (37 sources, 135 headers) in 1.77 sec: 12,931 declarations; 71,555 references; 2 unresolved inclusions; 137 syntax errors; 158 unresolved names (0.19%)

!ENTRY org.eclipse.jface 2 0 2021-06-03 17:23:11.923
!MESSAGE Ignored reentrant call while viewer is busy. This is only logged once per viewer instance, but similar calls will still be ignored.
!STACK 0
java.lang.RuntimeException
	at org.eclipse.jface.viewers.ColumnViewer.checkBusy(ColumnViewer.java:764)
	at org.eclipse.jface.viewers.ColumnViewer.update(ColumnViewer.java:543)
	at org.eclipse.ui.navigator.CommonViewer.update(CommonViewer.java:512)
	at org.eclipse.jface.viewers.StructuredViewer.update(StructuredViewer.java:1965)
	at org.eclipse.ui.internal.navigator.resources.nested.NestedProjectsLabelProvider.lambda$2(NestedProjectsLabelProvider.java:87)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

!ENTRY org.eclipse.cdt.debug.ui.memory.transport 4 5012 2021-06-03 17:34:56.151
!MESSAGE Could not write to file.
!STACK 0
java.io.FileNotFoundException: D:\GitHub\STM32f7_freeRTOS\C1\Records\001.SVdat (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.eclipse.cdt.debug.ui.memory.transport.RAWBinaryExporter$7.run(RAWBinaryExporter.java:467)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.cdt.debug.ui.memory.transport 4 5012 2021-06-03 17:34:56.154
!MESSAGE Could not write to file.
!STACK 0
java.io.FileNotFoundException: D:\GitHub\STM32f7_freeRTOS\C1\Records\001.SVdat (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.eclipse.cdt.debug.ui.memory.transport.RAWBinaryExporter$7.run(RAWBinaryExporter.java:467)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
